#MAIN PANEL SIZES
WINDOW_SIZE = (520, 505)
GUI_MAIN_H_GAP=3
GUI_MAIN_V_GAP=2
#BORDERS OF THE MAIN PANEL
BORDERSIZE_LEFTPAD = 2
BORDERSIZE_RIGHTPAD = 2
BORDERSIZE_BOTTOMPAD = 2
#GENERAL SIZE OF THE ITEMS
BORDERSIZE_SECTIONS = 1
BORDERSIZE_FORMATBOX = 1
BORDERSIZE_OPTIONS = 1
BORDERSIZE_SUBSECTION = 2
STANDARD_SECTION_FONT_SIZE = 9
#LOGWINDOW ITEM
LOGWINDOW_VERTICAL_SIZE = 45
LOGWINDOW_TEXT_FONT_SIZE=8
#FRAME ITEM
BORDER_SETTINGS_SECTION_MIN_X_SIZE = 325
#INPUT/OUTPUT PREVIEW ITEM
IMAGE_PREVIEW_SIZE = (128,128)
IMAGE_PREVIEW_BORDER_SIZE = (130,130)
INPUT_LIST_FONTSIZE=7
OUTPUT_LIST_FONTSIZE=7
IP_FOLDERICON_BORDER = 5
IP_FOLDERICON_TEXTAREA = 20
IP_FOLDERICON_EMOJI_FONT_MAX = 50
IP_FOLDERICON_EMOJI_FONT_MIN = 15
IP_FOLDERICON_TEXT_FONT = 7
#FORMAT SECTION ITEM
FORMAT_OPTION_CHECKBOX_PAD = 10
FORMAT_OPTION_SUBSECTION_DDS_INDENT = 4
FORMAT_OPTION_SUBSECTION_BLP_INDENT = 3
FORMAT_OPTION_SUBSECTION_TGA_INDENT = 7
DDS_OPTION_TYPEWINDOW_SIZE = 50
DDS_OPTION_MIPMAPWINDOW_SIZE  = 50
BLP_OPTION_SLIDER_SIZE = 100
BLP_OPTION_NUMERICWINDOW_SIZE = 50
BLP_OPTION_MIPMAPWINDOW_SIZE  = 50
FORMAT_GRID_SIZER_V_GAP = 0
FORMAT_GRID_SIZER_H_GAP = 5
FORMAT_EMPTY_SUBSECTION_SIZE = 50
#BUTTONS ITEM
PADSIZE_BUTTONS = 2
BUTTON_BIG_MIN_X_SIZE = 80
BUTTON_SMALL_MIN_X_SIZE = 64
#OUTPUT SECTION ITEM
OUTPUT_BASENAME_MIN_SIZE=75
OUTPUT_BASENAME_MAX_SIZE=128
OUTPUT_BASENAME_TITLE_PAD=3
#TOOLTIP
TOOLTIP_BORDER = 2
TOOLTIP_HOVER_PANEL_ADD_MARGIN_X = 3
TOOLTIP_HOVER_PANEL_ADD_MARGIN_Y = 0
#VALID FORMATS OPTION
VF_PAD_PER_ITEM = 2
VF_PAD_EXTRA = 10
VF_MAX_CHOICE_INT = 3
VF_WINDOW_SIZE  = 100
#ABOUT WINDOW
AW_MAX_THANKS_WIDTH = 320

